dist: trusty
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-keys
  - secure: Rv/8dLZU/dsbfRVj2gWXysnNhtZwbfUwPChAVY7P9cImD+Q/dYSnuhZ1RMJne/hrWwwZsn1O3icWF8FmlL3ztCqRIl+S6p1P4M+IEZO1EBBOrYiwqVj9uuZMtSY4oYuHl6/itfqrmDjN2zcUHbslBcfommwZ79n3kmHWjK85Pbj0YRwyKJur0NhSW/vg06O6E9idRYXhyryNx9/oqlSW6W7ppLbA7b+6CrimAfR4NVEyzq9HGTwImMKqvJiOtAzTCDEUQKxmk1k3p5HxF30dLA/IgjObgSlZ+Tn5neJQnSNDU71LSvOVY6tWC779UvN8njvQ5OnQFtVWxMX7+ahLg2bj6ELEyHvlF2oWZg0LTEKTNvzgGQ28bFIgoCqsaejawP3WiLCY0SLJDBpJHD+oabJ6l5eP2USUnZsDIk59kcNWnzvkkbc3780FYF902xA02g/kDc0UdPTOkFOqyJ0kVFf/PG6QzCFWME6P9I0jwHLlaYT7N2pqruEDZOxKIF6pSE+upvhPbH/7VfvZnkdOvhboiakdoK7WTYhqwwMsMQcwuP1pPwBCoXgWbqdyoSopaXg0BRP2RSNnDiaM8R8OZPH1fAFVkDEjjGIDGM6ig9AsWhOGHoKjRup8EifEpAeXMzf5xoIt2KSgUH/YOJY1Xk/Hd9bU970ai4YqvgUb+QE=
  - secure: d0VzTE0L0BG46b5DwbS+hOkBoLFKW+dR0nt3Z+ERBjT9yOCa8n6no77BRWXjfbIwACfEJlcaL7iOA465IJ0H34qjbJYfZKdstpxmQrQFgtsg3X8CAzzeMOaFuJdkaEbpTtu377b8p1bLauq7JxAxqFQlFSgdOWq0XEuONZnQ87b/nEolmm2VJkWY96Rv2OnF/if+XNQHIGJ7i6Ne9/Sutyj7KDaZQrVYziOiyclmnZD6JQWzG0fuyxTlwwxNKMefpYgDIbT2YoaneVTDyZwchJ5yRVJ40CYw9jTRmviTKymLyXFKi/ZUg9BWxmI+bwjy3lTutOJWn5xhrwI7HTh7fNybQpOFgJdZT4rqxNdE6DhokK5MhFVnNB8TlzvzG90f5FHrEBPs0/H41UAzwMC+HHl4soPaMaT03jgcZIuaVhFF44GDNsBbQI3llIZYfS/jYjhj7lcDaT6Oqv0uSYHkMzQ4TIeZ4PL7k+andZIc5nwK4/9Zcz99m8+natyv7z0+9b9ySPKNY91qnkqk1knz+VCG35W+iyLojetHN/AJ+jErYwi/lDCPotfhN2qeb0ResshQg/dOJ5ErfUWEOyCFFFExXwD1iP5Pw9DVOG+wUaJe0R0iW/AOUoc2boY4PUQXZUSVwR88u4fWvNYMKyzNcSKP/RAE63ptYJqT6qV9TMI=
before_install:
- pip install --user awscli
install:
- rvm install $(cat .circle-ruby)
- rvm-exec $(cat .circle-ruby) bundle install
script: rvm-exec $(cat .circle-ruby) bundle exec rake
deploy:
  provider: script
  script: aws s3 sync --delete _build/ s3://$BUCKET/ || travis_terminate 1
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: CGgI/KYiXPoJ3g06ovppN7GfR1waz9pyb3YPvg0gVuc7/Rb3a6o5X8++ruI1/xx7vtmOkxbbk+m2ZTDMIhHGNP7IPUhP4VmJizJLu9rVEuWHuDwSKABnPQ5wjjmBGJj8bkHJHARcPiPE6P5ZOd4wyJZsMXbXEp91NfJnu2iHjVf19aR/kL70iJG0/xaprCSnyQwiLoLQBSz9J4IuEFHbzBLXRKq2RhpAZUOxnZBypbryn0f5biEjZHA410vExhuO4ISaMJYcgr93pOacJmIiuiL4r7dxhT+0UxOrBKzUXMPHzmGwgzac3kj/bG7KkPxy/e2ypkZnhoVHvrr+J49OWAkm3PzorATiyvR5hIvricq0+lcdMYzsoLixfWWSV/9jZQKVugwiWpfcXUAFfAu4S0XZkJrS5BVhDpH6AnsbXC7FSgQD1ftwHRRu+dmMG4nmaXjbZG0SnAWlifKuWtJXW7eXrgr5l0tSKnhzQDNx3Rasyw0cOmvwlYm4QtQqdYCgc2kth9vlEkfceuHoomkKFR8EteBJUwnXDMQoDkm2mjOkym7rBcmG+hdZlc/8yzzkSSc8m85p51nAucIYP+tgfYNEPqLjtgUxlVnUUggxnK6vNsB92WMSHriJ7Wf42Tu7T+i46gmObUgCwm57y3HQNwyrRoKdXyWUa0jTxDstoDE=
