---
destination: _build
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- circle.yml
- Rakefile
- vendor
collections:
  groups:
    output: true
defaults:
- scope:
    type: groups
  values:
    layout: list
repo_url: 'https://github.com/akerl/keys'
host_url: 'https://id-ed25519.pub'
...
